# @package _global_
compress_factor: 4
mel_dim: 100
latent_dim: 64
sample_rate: 24000
mix_attributes_strategy: concat
semantic_quantizer_config:
  enabled: true
  hidden_dim: 256
  quant_dim: 64
  num_sem_blocks: 2
  num_pros_blocks: 2
  recon_weight: 0.0
  vq_config:
    num_embeddings: 1024
    drop_acoustic_p: 0.0
    vq_type: vq_ema
    vq_dim: 64
    commitment_weight: 0.25
    ema_decay: 0.99
    ema_eps: 1e-5
    reset_dead_codes: true
    reset_every_forward: 100
    entropy_loss_weight: 0.0
    entropy_temperature: 1.0
    dim_to_quantize: null
    recon_weight: null

training:
  dataset_name: libritts-r
  from_pretrained: /scratch/piermel/MelCausalVAE/checkpoints/paper/baseline/18-denc128-novq

  num_train_epochs: 3
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1

  output_dir: /scratch/piermel/MelCausalVAE/checkpoints/paper/baseline/18-denc128-novq/de2e
  save_total_limit: 3
  save_steps: 5000
  logging_steps: 10
  eval_strategy: steps
  eval_steps: 5000
  load_best_model_at_end: false
  metric_for_best_model: eval_avg_dWER
  greater_is_better: false
  eval_num_samples: 100

  learning_rate: 3.0e-5
  encoder_lr: 3.0e-5
  decoder_lr: 3.0e-5
  encoder_warmup_ratio: 0.03
  decoder_warmup_ratio: 0.03
  lr_scheduler_type: cosine
  min_learning_rate: 0.0
  encoder_min_lr: 1.0e-5
  decoder_min_lr: 1.0e-5
  max_grad_norm: 1.0

  report_to: wandb
  wandb_project: dicodec
  wandb_run_name: dicodec-18-de2e-vq-ema

  fp16: false
  bf16: true
  dataloader_num_workers: 8
  dataloader_prefetch_factor: 1
  dataloader_persistent_workers: true
  dataloader_pin_memory: false
  dataloader_drop_last: true

encoder:
  d_model: 128
  tf_heads: 8
  tf_layers: 4
  n_residual_blocks: 3
  logvar_layer: false
  target_std: 1.0
  kl_loss_warmup_ratio: 0.1
  kl_loss_weight: 1e-5
  use_reparameterization_trick: false
  use_std_sweep: true
  vq_config: null
  dropout_regularizer_config: null
  kl_chunk_regularizer_config: null
  noise_regularizer_config: null

decoder:
  dit_dim: 768
  dit_depth: 6
  dit_heads: 12
  dit_dropout_rate: 0.1
  use_conv_layer: true
  uncond_prob: 0.15
  is_causal: true
  use_window_attention: true
  window_attention_seconds: 3
  kernel_size: 17
  causal_convolution: false
  normalize_context_vector: true
  speaker_cond_dim: 1024
  local_speaker_conditioning: false

wavlm_module_config:
  pretrained_model_name: microsoft/wavlm-large
  feature_extractor_config:
    layer: 18
    sampling_rate: 16000
    normalize: true
  speaker_encoder_config:
    sampling_rate: 16000
    embedding_dim: 1024
    wavlm_layers:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    wavlm_layer_combine: weighted_sum
    wavlm_pooling: mean_std
    wavlm_layer_weights: null
    wavlm_normalize_features: true
    wavlm_freeze: true
    wavlm_attention_channels: 128
