# @package _global_
encoder:
  latent_dim: null
  mel_dim: null
  d_model: null
  compress_factor_C: null
  tf_heads: null
  tf_layers: null
  drop_p: 0.1
  n_residual_blocks: 3
  
  logvar_layer: true
  kl_loss_weight: 1.0e-5
  target_std: null
  kl_loss_warmup_steps: null
  kl_loss_warmup_ratio: null
  use_slt: false
  use_softplus: false
  use_reparameterization_trick: false
  use_std_sweep: false

  vq_config: null

  # Optional Regularizers
  dropout_regularizer_config: null
  kl_chunk_regularizer_config: null
  noise_regularizer_config: null
