# @package _global_
encoder:
  d_model: 512
  tf_heads: 8
  tf_layers: 4
  drop_p: 0.1
  n_residual_blocks: 3
  freeze_encoder_before_latent_heads: false
  
  logvar_layer: true
  kl_loss_weight: 1.0e-3
  target_std: null
  kl_loss_warmup_steps: 1000
  kl_loss_warmup_ratio: null
  use_slt: false
  use_softplus: false
  use_reparameterization_trick: false
  use_instance_norm: false

  # --- VQ ---
  vq_config:
    num_embeddings: null
    dim_to_quantize: null
    add_residual: false
    drop_acoustic_p: 0.0

  dropout_regularizer_config: null
    # chunk_size: 2
    # dropout_start: 0.0
    # dropout_end: 0.8
    # dropout_hierarchical: false

  kl_chunk_regularizer_config: null
    # chunk_size: 2
    # kl_weight_start: 1.0e-10
    # kl_weight_end: 1.0e-2
