# @package _global_
mel_dim: null
latent_dim: null
sample_rate: null
compress_factor: null
mix_attributes_strategy: add
semantic_quantizer_config:
  enabled: false
  hidden_dim: 256
  quant_dim: null
  num_sem_blocks: 2
  num_pros_blocks: 2
  kernel_size: 3
  recon_weight: 0.0
  vq_config: null
mel_spectrogram_config:
  sampling_rate: null
  n_fft: 1024
  hop_length: 256
  n_mels: 100
  padding: center
  normalize: true
