training:
  dataset_name: librispeech-align
  output_dir: checkpoints/MelCausalVAE/normal # variable rate training
  num_train_epochs: 5
  learning_rate: 1e-4
  per_device_train_batch_size: 24
  report_to: wandb
  wandb_project: flexi-vae
  wandb_run_name: normal
  fp16: false
  bf16: true
  save_steps: 1000
  eval_strategy: "steps"
  eval_steps: 1000
  save_total_limit: 1
  gradient_accumulation_steps: 1
  dataloader_num_workers: 4
  min_learning_rate: 5e-5
  #from_pretrained: /workspace/MelCausalVAE/checkpoints/MelCausalVAE/MFA-mean/checkpoint-68000/model.safetensors
  #resume_from_checkpoint: /workspace/MelCausalVAE/checkpoints/MelCausalVAE/MFA-attention-only-frames/checkpoint-38000
  phonemes: true

convformer:
  d_model: 512
  compress_factor_C: 1
  tf_heads: 8
  tf_layers: 2
  latent_dim: 64
  logvar_layer: false
  use_sofplus: false
  target_std: 1.0
  kl_loss_warmup_steps: 1000
  kl_loss_weight: 1e-4
  use_aligner: false
  n_residual_blocks: 4
  force_downsample: true # this with compress_factor_C=1 is equivalent to no downsample
  segment_embedding_scale: 1.0
  use_segment_embedding_residual: false

cfm:
  block_causal_mask: false
  unet_dim: 512
  unet_depth: 4
  unet_heads: 8
  unet_dropout_rate: 0.1
  use_conv_layer: true
  audio_latent_dim: 64
  uncond_prob: 0.15
  learned_prior: false
  is_causal: true
  decoder_type: "dit"