training:
  dataset_name: librispeech-align
  train_only_aligner: false
  output_dir: checkpoints/MelCausalVAE/qformer # variable rate training
  num_train_epochs: 5
  learning_rate: 1e-4
  per_device_train_batch_size: 4
  report_to: wandb
  wandb_project: flexi-vae
  wandb_run_name: qformer
  fp16: false
  bf16: true
  save_steps: 1000
  eval_strategy: "steps"
  eval_steps: 1000
  save_total_limit: 1
  gradient_accumulation_steps: 2
  dataloader_num_workers: 4
  min_learning_rate: 1e-6
  from_pretrained: /workspace/MelCausalVAE/checkpoints/MelCausalVAE/qformer/checkpoint-3000/model.safetensors
  #resume_from_checkpoint: /workspace/MelCausalVAE/checkpoints/MelCausalVAE/logvar/checkpoint-2000
  phonemes: true

convformer:
  compress_factor_C: 1
  tf_heads: 8
  tf_layers: 4
  latent_dim: 64
  logvar_layer: false
  use_sofplus: false
  target_std: 1.0
  kl_loss_warmup_steps: 500
  kl_loss_weight: 1.0
  use_aligner: true
  freeze_encoder: false
  threshold: 0.90

cfm:
  unet_dim: 1024
  unet_depth: 4
  unet_heads: 8
  unet_dropout_rate: 0.1
  use_conv_layer: true
  audio_latent_dim: 64
  uncond_prob: 0.15
  learned_prior: false
  is_causal: true
  decoder_type: "dit"